hello:
  test: HELLO11


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wiki
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root


mybatis:
  mapper-locations: classpath:/mapper/**/*.xml


